POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json

{
    "username": "Sukanya",
    "password": "sukanya1234",
    "email": "sukanya@example.com",
    "name": "Sukanya"
}

###

POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json

{
   
    "email": "test@example.com",
    "password": "test1234"
}


###
POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json

{
   
    "email": "sukanya@example.com",
    "password": "sukanya1234"
}


###

GET http://localhost:9090/get_user_and_profile
Content-Type: application/json

{
    "token": "6f0beda365b32840f05db706c62b981c1e25d960d0a53b77f315bfb12c46cb96"
}

###

POST http://localhost:9090/update_profile_data
Content-Type: application/json

{
    "token": "6f0beda365b32840f05db706c62b981c1e25d960d0a53b77f315bfb12c46cb96",
    "bio": "AI enthusiast and developer",
    "currentPost": "CTO",
    "pastWork": [
        {
            "company": "Microsoft",
            "position": "CTO",
            "years": "2+"
        }
    ],
    "education" : [
        {
            "school": "IIT",
            "degree": "Btech",
            "fieldOfStudy": "2015-2019"
        }
    ]
}


###
GET  http://localhost:9090/user/get_all_users